"""autogenerate likes table

Revision ID: f0746d9359ca
Revises: f6781e4cc5ab
Create Date: 2023-03-03 18:26:43.750208

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f0746d9359ca"
down_revision = "f6781e4cc5ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "likes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    op.alter_column(
        "posts",
        "publish",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts",
        "publish",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.drop_table("likes")
    # ### end Alembic commands ###
